#!/bin/bash

# close tunnel if argument is "off"
if [ "$1" = "off" ]; then
	sudo ifconfig gif0 destroy 2>/dev/null
	echo "tunnel closed"
	exit 0
fi

router=59.66.4.50
gateway=2001:da8:200:900e::1
prefix=2001:da8:200:900e::5efe

# test default gateway
err=`ping -q -W 1 -c 1 \`netstat -f inet -nr | grep '^default' | grep '\.' | awk '{print $2}'\` 1>/dev/null 2>&1 || echo '1'`
if [ -n "$err" ]; then
	echo 'failed to access default gateway'
	exit 1
fi

# test isatap router
err=`ping -q -W 1 -c 1 $router 1>/dev/null 2>&1 || echo '1'`
if [ -n "$err" ]; then
	echo 'failed to access isatap router'
	exit 1
fi

# get external ip address
ipecho_srv=(
[0]='ip.3322.net'
[1]='ipecho.net/plain'
)
for srv in ${ipecho_srv[@]}; do
	inet4=`curl $srv 2>/dev/null`
	if [ -n "$inet4" ]; then
		break
	fi
done
if [ -z "$inet4" ]; then
	echo 'failed to get external ip address'
	exit 1
fi

# recreate gif0
sudo ifconfig gif0 destroy 2>/dev/null
sudo ifconfig gif0 create 2>/dev/null

# set ipv6 address
inet6=$prefix:$inet4
sudo ifconfig gif0 inet6 $inet6 prefixlen 64

# set tunnel
sudo ifconfig gif0 tunnel $inet4 $router

# set route
sudo route delete -inet6 default 1>/dev/null 2>&1
sudo route add -inet6 default $gateway 1>/dev/null

# flush dns
sudo dscacheutil -flushcache

# echo result
inet4=`ifconfig gif0 | grep tunnel | awk '{print $3}'`
inet6=`ifconfig gif0 | grep inet6 | grep $prefix | awk '{print $2'}`
router=`ifconfig gif0 | grep tunnel | awk '{print $5}'`
gateway=`route get -inet6 default | grep gateway | awk '{print $2}'`
echo
echo 'tunnel  '$inet4' --> '$router
echo 'inet6   '$inet6
echo 'gateway '$gateway
echo

# ping6 test
ipv6_srv=(
[0]='ipv6.tsinghua.edu.cn'
[1]='ipv6.google.com'
[2]='bt.byr.cn'
[3]='bt.neu6.edu.cn'
)
for srv in ${ipv6_srv[@]}; do
	echo -n 'ping6 '$srv' ... '
	ping6 -q -i 1 -c 1 $srv 1>/dev/null 2>&1 && echo 'ok' || echo 'failed'
done
echo
