#!/bin/bash

function check_root {
    if [[ $EUID -ne 0 ]]; then
       echo "You must be root." 1>&2
       exit 1
    fi
}

function isatap_on {
    check_root
    echo -n "Enabling ISATAP ... "
    router=59.66.4.50
    gateway=2001:da8:200:900e::1
    prefix=2001:da8:200:900e::5efe
    inet4=`ifconfig | grep inet | grep -v inet6 | awk '{print $2}' | grep -v "^127.0.0.1$" | grep -v "^169.254" | grep -v "^192.168" | head -n 1`
    ifconfig gif0 destroy 2>/dev/null
    ifconfig gif0 create
    inet6=$prefix:$inet4
    ifconfig gif0 inet6 $inet6 prefixlen 64
    ifconfig gif0 tunnel $inet4 $router
    route delete -inet6 default 1>/dev/null 2>&1
    route add -inet6 default $gateway 1>/dev/null
    dscacheutil -flushcache
    echo "done"
}

function isatap_off {
    check_root
    echo -n "Disabling ISATAP ... "
    ifconfig gif0 destroy 2>/dev/null
    route delete -inet6 default 1>/dev/null 2>&1
    echo "done"
}

function isatap_test {
    ipv6_srv=(
        [0]='ipv6.tsinghua.edu.cn'
        [1]='ipv6.google.com'
        [2]='bt.byr.cn'
        [3]='bt.neu6.edu.cn'
    )
    for srv in ${ipv6_srv[@]}; do
        echo -n "ping6 $srv ... "
        ping6 -q -i 1 -c 1 $srv 1>/dev/null 2>&1 && echo "ok" || echo "failed"
    done
}

case "$1" in
    on) isatap_on && isatap_test || exit 1;;
    off) isatap_off || exit 1;;
    status) isatap_status || exit 1;;
    test) isatap_test || exit 1;;
    *) echo "Options: on, off, test."
esac
